name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgl1 libegl1 libxkbcommon0
          version: 1.0
          
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install cython bottle cheroot brotli numpy scipy pytest
          pip install -e .[treeview,test,doc,render_sm,treediff]
      

      - name: Run tests
        run: |
          pytest tests -m "not interactive and not slow"
