name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libegl1 libxkbcommon0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install external executables
        run: |
          conda config --add channels bioconda
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install -y -c conda-forge mamba
          mamba install -y -c bioconda dialign-tx=1.0.2
          # DupTree is not available via conda or pip; build from source if needed
          mamba install -y -c bioconda fasttree
          mamba install -y -c bioconda t-coffee=11.00.8cbe486
          mamba install -y -c conda-forge argtable2=2.13
          mamba install -y -c bioconda clustalo=1.2.4
          mamba install -y -c bioconda consel
          mamba install -y -c bioconda iqtree=1.6.12
          mamba install -y -c bioconda kalign2=2.04
          mamba install -y -c bioconda mafft
          mamba install -y -c bioconda muscle=3.8.1551
          mamba install -y -c bioconda paml
          mamba install -y -c bioconda phylobayes-mpi
          mamba install -y -c bioconda phyml
          mamba install -y -c etetoolkit pmodeltest
          mamba install -y -c bioconda prank
          mamba install -y -c bioconda probcons=1.12
          mamba install -y -c bioconda raxml=8.2.13
          mamba install -y -c bioconda treebest
          mamba install -y -c bioconda trimal=1.5.0
        shell: bash -l {0}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython bottle cheroot brotli numpy scipy pytest
          pip install -e .[treeview,test,doc,render_sm,treediff]
        shell: bash -l {0}

      - name: Run tests
        run: |
          pytest tests -m "not interactive and not slow"
        shell: bash -l {0}
